name: Homeostasis Healing
on:
  workflow_run:
    workflows: ["CI", "Build", "Test"]
    types: [completed]
  workflow_dispatch:
    inputs:
      confidence_threshold:
        description: 'Minimum confidence for auto-healing'
        required: false
        default: '0.8'
        type: string

jobs:
  analyze-and-heal:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Homeostasis
      run: |
        python -m pip install --upgrade pip
        pip install homeostasis[github]
    
    - name: Analyze workflow failure
      id: analyze
      run: |
        if [ "${{ github.event_name }}" = "workflow_run" ]; then
          RUN_ID="${{ github.event.workflow_run.id }}"
        else
          # Get latest failed run
          RUN_ID=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.conclusion == "failure") | .id' | head -1)
        fi
        
        echo "Analyzing workflow run: $RUN_ID"
        homeostasis analyze-github-workflow \
          --run-id "$RUN_ID" \
          --repo "${{ github.repository }}" \
          --output analysis.json
        
        # Check if healing is recommended
        HEALING_NEEDED=$(jq -r '.healing_recommended' analysis.json)
        CONFIDENCE=$(jq -r '.confidence_score' analysis.json)
        
        echo "healing-needed=$HEALING_NEEDED" >> $GITHUB_OUTPUT
        echo "confidence-score=$CONFIDENCE" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Apply high-confidence fixes
      if: steps.analyze.outputs.healing-needed == 'true' && steps.analyze.outputs.confidence-score > 0.8
      run: |
        homeostasis heal \
          --input analysis.json \
          --auto-apply \
          --min-confidence ${{ github.event.inputs.confidence_threshold || '0.8' }}
        
        # Test the fixes
        if [ -f "package.json" ]; then
          npm test || echo "Tests failed, but continuing with healing"
        elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
          python -m pytest || echo "Tests failed, but continuing with healing"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit automatic fixes
      if: steps.analyze.outputs.healing-needed == 'true' && steps.analyze.outputs.confidence-score > 0.8
      run: |
        git config --local user.email "homeostasis[bot]@users.noreply.github.com"
        git config --local user.name "Homeostasis Bot"
        
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "🔧 Auto-heal: Apply high-confidence fixes
          
          - Applied fixes with confidence > ${{ steps.analyze.outputs.confidence-score }}
          - Workflow run: ${{ github.event.workflow_run.html_url || github.server_url }}/${{ github.repository }}/actions
          - Generated by Homeostasis"
          git push
        fi
    
    - name: Create PR for manual review
      if: steps.analyze.outputs.healing-needed == 'true' && steps.analyze.outputs.confidence-score <= 0.8
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          🔧 Homeostasis: Suggested fixes for workflow failures
          
          - Confidence score: ${{ steps.analyze.outputs.confidence-score }}
          - Requires manual review before merging
        title: '🔧 Homeostasis: Healing suggestions (review required)'
        body: |
          ## 🔧 Homeostasis Healing Suggestions
          
          This PR contains automated healing suggestions for recent workflow failures.
          
          **Confidence Score:** ${{ steps.analyze.outputs.confidence-score }}
          
          **Analysis Results:**
          ```json
          $(cat analysis.json)
          ```
          
          **Please review these changes carefully before merging.**
          
          ---
          *Generated by [Homeostasis](https://github.com/homeostasis-framework/homeostasis) 🤖*
        branch: homeostasis/healing-suggestions
        delete-branch: true
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: homeostasis-analysis
        path: analysis.json
        retention-days: 30