name: Quick Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libldap2-dev libsasl2-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-timeout pytest-xdist
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run linting
      run: |
        pip install flake8
        flake8 modules/ services/ orchestrator/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run quick unit tests
      env:
        USE_MOCK_TESTS: true
        DISABLE_PERFORMANCE_TRACKING: true
        CI: true
        GITHUB_ACTIONS: true
      run: |
        echo "Running quick unit tests..."
        python -m pytest tests/unit/ \
          --timeout=30 \
          --timeout-method=thread \
          -x \
          --tb=short \
          -v

    - name: Run critical integration tests
      env:
        USE_MOCK_TESTS: true
        DISABLE_PERFORMANCE_TRACKING: true
        CI: true
        GITHUB_ACTIONS: true
      run: |
        echo "Running critical integration tests..."
        python -m pytest tests/integration/ \
          --timeout=60 \
          --timeout-method=thread \
          -x \
          --tb=short \
          -v