name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Quick lint check first
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Lint check
      run: |
        python -m pip install --upgrade pip flake8
        flake8 modules/ services/ orchestrator/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

  # Trigger quick tests
  quick-tests:
    needs: lint
    uses: ./.github/workflows/ci-quick-tests.yml

  # Trigger parallel test workflows
  language-tests:
    needs: lint
    uses: ./.github/workflows/ci-language-plugins.yml

  e2e-integration:
    needs: lint
    uses: ./.github/workflows/e2e-healing-tests.yml

  main-suite:
    needs: lint
    uses: ./.github/workflows/ci-other.yml

  # Final status check
  ci-complete:
    needs: [quick-tests, language-tests, e2e-integration, main-suite]
    if: always()
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - name: Check all test results
      run: |
        echo "Test Results Summary:"
        echo "===================="
        echo "Quick Tests: ${{ needs.quick-tests.result }}"
        echo "Language Tests: ${{ needs.language-tests.result }}"
        echo "E2E/Integration: ${{ needs.e2e-integration.result }}"
        echo "Main Suite: ${{ needs.main-suite.result }}"

        # Fail if any test suite failed
        if [[ "${{ needs.quick-tests.result }}" == "failure" ]] || \
           [[ "${{ needs.language-tests.result }}" == "failure" ]] || \
           [[ "${{ needs.e2e-integration.result }}" == "failure" ]] || \
           [[ "${{ needs.main-suite.result }}" == "failure" ]]; then
          echo ""
          echo "One or more test suites failed!"
          exit 1
        else
          echo ""
          echo "All test suites passed!"
        fi